/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-03-21 00:17:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/common/header.jsp", Long.valueOf(1679357551083L));
    _jspx_dependants.put("/views/common/body_right.jsp", Long.valueOf(1679357551082L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/CSS/header.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/CSS/body.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/CSS/footer.css\">\r\n");
      out.write("    <title>KH_TIME 메인페이지</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("    * {\r\n");
      out.write("        border: 1px solid rgba(128, 128, 128, 0.568);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    div {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #wrapper {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        min-width: 1180px;\r\n");
      out.write("        background-color: #f1f4f9;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/CSS/header.css\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"header\">\r\n");
      out.write("        <div id=\"header-content\">\r\n");
      out.write("            <div id=\"home-logo\">\r\n");
      out.write("                <img src=\"");
      out.print( request.getContextPath());
      out.write("/resources/IMG/로고이미지.png\" alt=\"로고이미지\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"navbar\">\r\n");
      out.write("                <div>게시판</div>\r\n");
      out.write("                <div>친구목록</div>\r\n");
      out.write("                <div id=\"bookstore\">중고책방</div>\r\n");
      out.write("                <div id=\"todolist\">To Do List</div>\r\n");
      out.write("                <div>관리</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"header-right\">\r\n");
      out.write("                <button id=\"login-btn\">로그인</button>\r\n");
      out.write("                <button id=\"enrollment-btn\">회원가입</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    \r\n");
      out.write("	    document.getElementById(\"home-logo\").addEventListener(\"click\",function(){\r\n");
      out.write("	        location.href = \"");
      out.print( request.getContextPath() );
      out.write("\";\r\n");
      out.write("	    })\r\n");
      out.write("        \r\n");
      out.write("        document.getElementById(\"login-btn\").addEventListener(\"click\",function(){\r\n");
      out.write("            location.href = \"");
      out.print( request.getContextPath() );
      out.write("/login.me\";\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        document.getElementById(\"enrollment-btn\").addEventListener(\"click\",function(){\r\n");
      out.write("            location.href = \"");
      out.print( request.getContextPath() );
      out.write("/enroll.me\";\r\n");
      out.write("        })\r\n");
      out.write("        \r\n");
      out.write("         document.getElementById(\"todolist\").addEventListener(\"click\",function(){\r\n");
      out.write("            location.href = \"");
      out.print( request.getContextPath() );
      out.write("/todolist.me\";\r\n");
      out.write("        })\r\n");
      out.write("        \r\n");
      out.write("        document.getElementById(\"bookstore\").addEventListener(\"click\",function(){\r\n");
      out.write("            location.href = \"");
      out.print( request.getContextPath() );
      out.write("/bookstore.do\";\r\n");
      out.write("        })\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"body\">\r\n");
      out.write("            <div id=\"main-banner\">\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"body-wrapper\">\r\n");
      out.write("                <div id=\"body-left\">\r\n");
      out.write("                    <div id=\"board-wrapper\">\r\n");
      out.write("                        <table id=\"board-1\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th id=\"test1\"></th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목1</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목2</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목3</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목4</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목5</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목6</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("\r\n");
      out.write("                        </table>\r\n");
      out.write("                        <table id=\"board-2\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>질문답변게시판</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목1</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목2</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목3</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목4</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목5</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목6</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                        <table id=\"board-3\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>프로젝트 및 스터디 모집 게시판</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목1</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목2</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목3</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목4</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목5</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목6</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                        <table id=\"board-4\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>수료생 게시판</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목1</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목2</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목3</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목4</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목5</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목6</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                        <table id=\"board-5\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>건의사항 게시판</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목1</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목2</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목3</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목4</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목5</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목6</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                        <table id=\"board-6\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>공지사항 게시판</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목1</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목2</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목3</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목4</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목5</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>게시물 제목6</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"books-wrapper\">\r\n");
      out.write("                        <div id=\"book-1\">\r\n");
      out.write("                            <div class=\"book-img\">\r\n");
      out.write("                                <img src=\"resources/IMG/책이미지.jfif\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"book-text\">\r\n");
      out.write("                                <div>책제목1</div>\r\n");
      out.write("                                <div>책가격1</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"book-2\">\r\n");
      out.write("                            <div class=\"book-img\">\r\n");
      out.write("                                <img src=\"resources/IMG/책이미지.jfif\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"book-text\">\r\n");
      out.write("                                <div>책제목2</div>\r\n");
      out.write("                                <div>책가격2</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"book-3\">\r\n");
      out.write("                            <div class=\"book-img\">\r\n");
      out.write("                                <img src=\"resources/IMG/책이미지.jfif\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"book-text\">\r\n");
      out.write("                                <div>책제목3</div>\r\n");
      out.write("                                <div>책가격3</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"book-4\">\r\n");
      out.write("                            <div class=\"book-img\">\r\n");
      out.write("                                <img src=\"resources/IMG/책이미지.jfif\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"book-text\">\r\n");
      out.write("                                <div>책제목4</div>\r\n");
      out.write("                                <div>책가격4</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("		 ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/CSS/body.css\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"body-right\">\r\n");
      out.write("        <div id=\"search\">\r\n");
      out.write("                <img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/IMG/searchimg.png\" alt=\"searchimg\" width=\"40\" height=\"40\">\r\n");
      out.write("                <input type=\"search\" id=\"search-input\" placeholder=\"전체 게시글의 글을 검색하세요\">         \r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"login\">\r\n");
      out.write("            <form action=\"\">\r\n");
      out.write("                <div id=\"id-wrapper\">\r\n");
      out.write("                    <img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/IMG/idimg.png\" alt=\"idimg\" width=\"40\" height=\"40\">\r\n");
      out.write("                    <input type=\"text\" id=\"login-id\" placeholder=\"아이디를 입력하세요\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pwd-wrapper\">\r\n");
      out.write("                    <img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/IMG/pwdimg.png\" alt=\"pwdimg\" width=\"40\" height=\"40\">\r\n");
      out.write("                    <input type=\"password\" id=\"login-pwd\" placeholder=\"비밀번호를 입력하세요\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"btn-wrapper\">\r\n");
      out.write("                    <input type=\"submit\" value=\"로그인\">\r\n");
      out.write("                    <input type=\"button\" value=\"회원가입\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"user-list\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/IMG/free-icon-billboard-773665.png\" alt=\"\" width=\"20\" height=\"20\">\r\n");
      out.write("                <div id=\"user-boards\">내가 쓴글</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/IMG/replyimg.png\" alt=\"\" width=\"20\" height=\"20\">\r\n");
      out.write("                <div id=\"user-replys\">내가 쓴 댓글</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/IMG/scrapimg.png\" alt=\"\" width=\"20\" height=\"20\">\r\n");
      out.write("                <div id=\"user-scraps\">스크랩한 글</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"additional-functions\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/IMG/free-icon-live-chat-5603000.png\" alt=\"\" width=\"20\" height=\"20\">\r\n");
      out.write("                <div id=\"realtime-chat\">실시간 채팅</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/IMG/free-icon-letter-d-5069823.png\" alt=\"\" width=\"20\" height=\"20\">\r\n");
      out.write("                <div id=\"d-day\">d-day알림</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/IMG/stopwatch.png\" alt=\"\" width=\"20\" height=\"20\">\r\n");
      out.write("                <div id=\"check-study-time\">공부량 체크</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"hot-board\">\r\n");
      out.write("            <table id=\"board-5\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>HOT 게시판</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>게시물 제목1</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>게시물 제목2</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>게시물 제목3</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>게시물 제목4</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>게시물 제목5</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>게시물 제목6</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"best-board\">\r\n");
      out.write("            <table id=\"board-6\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>BEST 게시판</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>게시물 제목1</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>게시물 제목2</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>게시물 제목3</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>게시물 제목4</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>게시물 제목5</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>게시물 제목6</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("	\r\n");
      out.write("        <div id=\"footer\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("<script>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	window.onload = function(){\r\n");
      out.write("	document.getElementById(\"test1\").innerHTML=\"Dd\";\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
